# ChromaShell — Kitty Terminal
# Colors are applied live by caelestia via ANSI sequences (cat ~/.local/state/caelestia/sequences.txt in fish)

# Font
font_family      JetBrains Mono Nerd Font
font_size        12.0
bold_text_in_bright no

# Cursor
cursor_shape        beam
cursor_beam_thickness 1.5
cursor_trail        1

# Padding
window_padding_width 25

# Scrollback
scrollback_lines    10000

# Shell
shell               fish
confirm_os_window_close 0

# Keybindings
map ctrl+c       copy_or_interrupt

map ctrl+f       launch --location=hsplit --allow-remote-control kitty +kitten search.py @active-kitty-window-id
map kitty_mod+f  launch --location=hsplit --allow-remote-control kitty +kitten search.py @active-kitty-window-id

map page_up      scroll_page_up
map page_down    scroll_page_down

map ctrl+plus         change_font_size all +1
map ctrl+equal        change_font_size all +1
map ctrl+kp_add       change_font_size all +1
map ctrl+minus        change_font_size all -1
map ctrl+underscore   change_font_size all -1
map ctrl+kp_subtract  change_font_size all -1
map ctrl+0            change_font_size all 0
map ctrl+kp_0         change_font_size all 0
