hl.env("NIXOS_OZONE_WL",                     "1")
hl.env("QT_QPA_PLATFORM",                    "wayland")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION","1")
hl.env("GDK_BACKEND",                        "wayland,x11")
hl.env("SDL_VIDEODRIVER",                    "wayland")
hl.env("CLUTTER_BACKEND",                    "wayland")
hl.env("XDG_CURRENT_DESKTOP",               "Hyprland")
hl.env("XDG_SESSION_TYPE",                   "wayland")
hl.env("XDG_SESSION_DESKTOP",               "Hyprland")
