# ══════════════════════════════════════════
#  ChromaShell — Window Rules
# ══════════════════════════════════════════

# Disable "Disable blur for xwayland context menus"
windowrule = match:class ^()$, match:title ^()$, no_blur off

# Disable "Disable blur for every window"
windowrule = match:class .*, no_blur off

windowrule = opacity 0.8 override 0.8 override, match:class .*

# Disable blur for video-like windows
windowrule = opacity 1.0 override, match:class ^(librewolf)$, match:title .*(YouTube|Twitch|Netflix|Prime Video|S.to|mp4).*
windowrule = no_blur on, match:class ^(librewolf)$, match:title .*(YouTube|Twitch|Netflix|Prime Video|S.to|mp4).*.
windowrule = opacity 1.0 override, match:class ^(mpv)$
windowrule = opacity 1.0 override, match:class ^(vlc)$
windowrule = no_blur on, match:class ^(mpv)$
windowrule = no_blur on, match:class ^(vlc)$

# Scratchpad terminal (Super+Space dropdown)
windowrule = float on, match:class ^(kitty-scratchpad)$
windowrule = size 100% 50%, match:class ^(kitty-scratchpad)$
windowrule = move 0% 0%, match:class ^(kitty-scratchpad)$
windowrule = workspace special:terminal silent, match:class ^(kitty-scratchpad)$
windowrule = rounding 0, match:class ^(kitty-scratchpad)$