# ══════════════════════════════════════════
#  ChromaShell — Window Rules
# ══════════════════════════════════════════

windowrule = float, class:(pavucontrol)
windowrule = float, class:(blueman-manager)
windowrule = float, class:(nm-connection-editor)
windowrule = float, title:(Picture-in-Picture)
windowrule = pin,   title:(Picture-in-Picture)
