# ══════════════════════════════════════════
#  ChromaShell — Variables
# ══════════════════════════════════════════

$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$launcher = rofi -show drun
