# ══════════════════════════════════════════
#  ChromaShell — Autostart
# ══════════════════════════════════════════

# --- Wallpaper ------------------------------
exec-once = awww-daemon

# --- Core components 
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = hypridle
exec-once = dbus-update-activation-environment --all
exec-once = sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # Some fix idk


# --- Media ----------------------------------
exec-once = playerctld

# --- Clipboard ------------------------------
exec-once = wl-paste --type text  --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# --- OSD ------------------------------------
exec-once = swayosd-server

# --- Audio ----------------------------------
exec-once = bash ~/.config/hypr/scripts/audio/start-jalv.sh
exec-once = sleep 2 && qpwgraph -a -m

# --- Shell ---------------------------------
exec-once = quickshell -c ChromaShell

# --- Cursor --------------------------------
exec-once = hyprctl setcursor Bibata-Modern-Classic 18

# --- Scratchpad terminal (hidden on start, toggle via Super+Space) ----------
exec-once = kitty --class kitty-scratchpad
