# ══════════════════════════════════════════
#  ChromaShell — Hyprland Entry Point
# ══════════════════════════════════════════

source = ~/.config/hypr/colors.conf

# ── ChromaShell upstream ───────────────────
source = ~/.config/hypr/config/variables.conf
source = ~/.config/hypr/config/env.conf
source = ~/.config/hypr/config/settings.conf
source = ~/.config/hypr/config/rules.conf
source = ~/.config/hypr/config/keybindings.conf
source = ~/.config/hypr/config/autostart.conf

# ── Per-machine (writable, created once by flake, never overwritten) ────────
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/workspaces.conf

# ── User custom (writable, created once by flake, never overwritten) ────────
source = ~/.config/hypr/custom/env.conf
source = ~/.config/hypr/custom/rules.conf
source = ~/.config/hypr/custom/keybindings.conf
source = ~/.config/hypr/custom/autostart.conf
