-- ══════════════════════════════════════════
--  ChromaShell — Hyprland Entry Point
-- ══════════════════════════════════════════

-- Colors (generated by matugen; falls back to defaults if not yet generated)
local ok, colors = pcall(require, "colors")
if not ok then
    colors = { active_border="rgba(0DB7D4FF)", inactive_border="rgba(31313600)" }
end
-- Expose colors globally so settings.lua can access via its own pcall(require,"colors")

-- ChromaShell upstream
require("config.variables")
require("config.env")
require("config.settings")
require("config.rules")
require("config.keybindings")
require("config.autostart")

-- Per-machine (writable, created once by flake, never overwritten)
require("monitors")
require("workspaces")

-- User custom (writable, created once by flake, never overwritten)
pcall(require, "custom.env")
pcall(require, "custom.rules")
pcall(require, "custom.keybindings")
pcall(require, "custom.autostart")
