-- ══════════════════════════════════════════
--  ChromaShell — Hyprland Entry Point
-- ══════════════════════════════════════════

-- Colors (generated by matugen; falls back to defaults if not yet generated)
local ok, colors = pcall(require, "colors")
if not ok then
    colors = { active_border="rgba(0DB7D4FF)", inactive_border="rgba(31313600)" }
end
-- Expose colors globally so settings.lua can access via its own pcall(require,"colors")

-- variables
require("config.variables")         -- upstream
pcall(require, "custom.variables")  -- custom (writable, created once by flake, never overwritten)
pcall(require, "generated.editor")  -- flake-managed: sets v.editor from editor.app option
pcall(require, "generated.browser") -- flake-managed: sets v.browser from browser.app option

-- ChromaShell upstream
require("config.env")
require("config.settings")
require("config.rules")
require("config.keybindings")
require("config.autostart")

-- Per-machine (writable, created once by flake, never overwritten)
require("monitors")
require("workspaces")

-- User custom (writable, created once by flake, never overwritten)
pcall(require, "custom.env")
pcall(require, "custom.rules")
pcall(require, "custom.keybindings")
pcall(require, "custom.autostart")
pcall(require, "custom.settings")   -- hl.config() calls merge, so end is fine
