-- Workspace rules — edit for your machine.
-- Each monitor must own exactly 10 contiguous workspaces starting at a multiple of 10 + 1.
-- This is required for wsaction.fish: floor((active_ws - 1) / 10) * 10 + slot
--
-- 2-monitor example:
--   hl.workspace_rule({ workspace="1",  monitor="DP-1", default=true })
--   ...
--   hl.workspace_rule({ workspace="10", monitor="DP-1" })
--   hl.workspace_rule({ workspace="11", monitor="DP-2", default=true })
--   ...
--   hl.workspace_rule({ workspace="20", monitor="DP-2" })
--
-- 3-monitor example: add workspaces 21-30 for the third monitor.
-- Run: hyprctl monitors | grep Monitor   to find output names.
