context.modules = [
  {   name  = libpipewire-module-filter-chain
      flags = [ nofail ]
      args  = {
          node.description = "Mic Chain"
          filter.graph = {
              nodes = [
                  { type = builtin  name = copy  label = copy }
              ]
              inputs  = [ "copy:In"  ]
              outputs = [ "copy:Out" ]
          }
          audio.channels  = 2
          audio.position  = [ FL FR ]
          capture.props = {
              node.name        = "mic_chain_in"
              node.description = "Mic Chain In"
              media.class      = "Audio/Sink"
          }
          playback.props = {
              node.name        = "mic_chain_out"
              node.description = "Mic Chain Out"
              media.class      = "Audio/Source"
              node.passive     = true
          }
      }
  }
]
