context.modules = [
    {   name = libpipewire-module-loopback
        args = {
            node.description = "Mix Bus"
            audio.position = [ FL FR ]
            capture.props = {
                media.class    = "Audio/Sink"
                node.name      = "MixBus.input"
                node.passive   = true
                stream.dont-remix = true
            }
            playback.props = {
                media.class = "Audio/Source"
                node.name   = "MixBus.output"
            }
        }
    }
    {   name = libpipewire-module-loopback
        args = {
            node.description = "Mix Bus Chat"
            audio.position = [ FL FR ]
            capture.props = {
                media.class       = "Audio/Sink"
                node.name         = "MixBusChat.input"
                node.passive      = true
                stream.dont-remix = true
                media.role        = "Communication"
                priority.session  = 1100
            }
            playback.props = {
                media.class = "Audio/Source"
                node.name   = "MixBusChat.output"
            }
        }
    }
    {   name = libpipewire-module-loopback
        args = {
            node.description = "Virtual Audio Cable"
            audio.position = [ FL FR ]
            capture.props = {
                media.class  = "Audio/Sink"
                node.name    = "VirtualCable.input"
                node.passive = true
            }
            playback.props = {
                media.class = "Audio/Source"
                node.name   = "VirtualCable.output"
            }
        }
    }
]
