#!/usr/bin/env bash
# Called by caelestia-cli after each theme change.
# $SCHEME_COLOURS is injected as a JSON object by caelestia-cli.
#
# Usage: caelestia-posthook.sh [--browser BROWSER] [--comms APP]

browser=""
comms=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --browser) browser="$2"; shift 2 ;;
        --comms)   comms="$2";   shift 2 ;;
        *) shift ;;
    esac
done

primary=$(jq -r '.primary' <<< "$SCHEME_COLOURS")
surface=$(jq -r '.surface'  <<< "$SCHEME_COLOURS")

# Hyprland border colors
printf 'return {\n  active_border   = "rgba(%sFF)",\n  inactive_border = "rgba(%s00)",\n}\n' \
    "$primary" "$surface" > "$HOME/.config/hypr/colors.lua"
hyprctl reload

# --- Zen browser ---
if [[ "$browser" == "zen" ]]; then
    mkdir -p "$HOME/.config/chromashell/theming/runtime"
    surface_container=$(jq -r '.surfaceContainer' <<< "$SCHEME_COLOURS")
    outline_variant=$(jq -r '.outlineVariant'    <<< "$SCHEME_COLOURS")
    surface_dim=$(jq -r '.surfaceDim'            <<< "$SCHEME_COLOURS")
    printf ':root {\n    --zen-primary-color: #%s !important;\n    --zen-colors-primary: #%s !important;\n    --zen-colors-secondary: #%s !important;\n    --zen-colors-tertiary: #%s !important;\n    --zen-colors-border: #%s !important;\n    --zen-themed-toolbar-bg: #%s !important;\n    --zen-main-browser-background: #%s !important;\n}\n' \
        "$surface_container" "$primary" "$surface_container" "$surface" \
        "$outline_variant" "$surface_dim" "$surface_dim" \
        > "$HOME/.config/chromashell/theming/runtime/zen-colors.css"
fi

# --- Element ---
if [[ "$comms" == "element" ]]; then
    on_surface=$(jq -r '.onSurface'              <<< "$SCHEME_COLOURS")
    on_surface_var=$(jq -r '.onSurfaceVariant'   <<< "$SCHEME_COLOURS")
    surface_cont=$(jq -r '.surfaceContainer'     <<< "$SCHEME_COLOURS")
    surface_cont_low=$(jq -r '.surfaceContainerLow'  <<< "$SCHEME_COLOURS")
    surface_cont_high=$(jq -r '.surfaceContainerHigh' <<< "$SCHEME_COLOURS")
    outline_var=$(jq -r '.outlineVariant'        <<< "$SCHEME_COLOURS")
    error_col=$(jq -r '.error'                   <<< "$SCHEME_COLOURS")
    primary_cont=$(jq -r '.primaryContainer'     <<< "$SCHEME_COLOURS")
    success_col=$(jq -r '.success // "4CAF50"'   <<< "$SCHEME_COLOURS")

    element_css="${XDG_CONFIG_HOME:-$HOME/.config}/chromashell/theming/runtime/element.css"
    mkdir -p "${XDG_CONFIG_HOME:-$HOME/.config}/chromashell/theming/runtime"

    cat > "$element_css" << EOF
/* ChromaShell — generated by caelestia postHook */
:root, .cpd-theme-dark, .cpd-theme-light {
    --cpd-color-theme-bg:                   #${surface} !important;
    --cpd-color-bg-canvas-default:          #${surface_cont} !important;
    --cpd-color-bg-subtle-secondary:        #${surface} !important;
    --cpd-color-bg-subtle-primary:          #${surface_cont_low} !important;
    --cpd-color-bg-action-primary-rest:     #${primary} !important;
    --cpd-color-bg-accent-rest:             #${primary} !important;
    --cpd-color-bg-critical-primary:        #${error_col} !important;
    --cpd-color-text-primary:               #${on_surface} !important;
    --cpd-color-text-secondary:             #${on_surface_var} !important;
    --cpd-color-text-action-accent:         #${primary} !important;
    --cpd-color-text-critical-primary:      #${error_col} !important;
    --cpd-color-text-success-primary:       #${success_col} !important;
    --cpd-color-icon-accent-tertiary:       #${primary} !important;
    --cpd-color-icon-primary:               #${on_surface} !important;
    --cpd-color-icon-secondary:             #${on_surface_var} !important;
    --cpd-color-icon-tertiary:              #${on_surface_var} !important;
    --cpd-color-border-interactive-primary: #${outline_var} !important;
    --cpd-color-border-critical-primary:    #${error_col} !important;
    --cpd-color-border-success-subtle:      #${success_col} !important;
}
EOF
fi
